import {
  Award,
  BadgeCheck,
  BarChart3,
  BookMarked,
  BookOpen,
  Bot,
  BrainCircuit,
  Boxes,
  Briefcase,
  Cloud,
  Cpu,
  Database,
  FileText,
  FolderKanban,
  GraduationCap,
  Infinity as InfinityIcon,
  Sparkles,
  Workflow,
  type LucideIcon,
} from "lucide-react";

// Resolves the icon-name strings used across the About data files to their
// lucide components, keeping the data layer free of React imports.
export const aboutIcons: Record<string, LucideIcon> = {
  Award,
  BadgeCheck,
  BarChart3,
  BookMarked,
  BookOpen,
  Bot,
  BrainCircuit,
  Boxes,
  Briefcase,
  Cloud,
  Cpu,
  Database,
  FileText,
  FolderKanban,
  GraduationCap,
  Infinity: InfinityIcon,
  Sparkles,
  Workflow,
};
